name: Commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Set permissions of GITHUB_TOKEN for dependabot
permissions:
  contents: write
  pull-requests: write
  packages: write
  checks: write

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Commit build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-packages-${{ hashFiles('Directory.Packages.props') }}
          restore-keys: |
            nuget-packages-

      - name: Build
        run: dotnet build
